-- Up  
ALTER TABLE users  
ALTER COLUMN id TYPE SMALLINT;
ALTER TABLE users  
ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;  
ALTER TABLE users  
ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;  

-- Down  
ALTER TABLE users  
ALTER COLUMN id TYPE BIGINT;  
ALTER TABLE users  
ALTER COLUMN created_at SET DATA TYPE TIMESTAMPTZ;  
ALTER TABLE users  
ALTER COLUMN updated_at SET DATA TYPE TIMESTAMPTZ;  